### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by oubiwann** [rvirding/luerl#102]
@rvirding asked me to give a try to creating a project logo, so this ticket is to track that work. I've taken some obvious inspiration from the project name ;-) (Portuguese for "moon"). Will attach drafts created so far ...

**Comment by oubiwann** [comment]
Draft 1: 
![LuErl-Logo-1-draft](https://user-images.githubusercontent.com/894251/57572016-fdd26680-73da-11e9-814f-31e0247e845d.png)

**Comment by oubiwann** [comment]
Draft 4:
![LuErl-Logo-4-draft](https://user-images.githubusercontent.com/894251/57572021-12166380-73db-11e9-8501-48522e7a07f8.png)

**Comment by oubiwann** [comment]
Note that while the attached drafts are rendered .png files, the work is being done on .svgs and the PR will include an .svg file ... maybe in an `./images` directory?

**Comment by jchassoul** [comment]
Hi @oubiwann I have been using the Lua logo for luerl since its an implementation of the Lua language a not a language-like Lua but its greet to have a logo for Luerl in order to differentiate and also I hear that awesome improvements are in some pipelines! (=

Can I send a proposal for the logo as well from members of the local talent here in Costa Rica?

**Comment by oubiwann** [comment]
By all means!!! My only desire is that @rvirding has something he likes :-D Looking forward to seeing other submissions!

**Comment by oubiwann** [comment]
In case you want to use the same source for the "Erlang" part, I created a vectorized version of the old Coca-Cola/Baseball-team themed Erlang logo:
![image](https://user-images.githubusercontent.com/894251/57877145-b124cc00-77dc-11e9-93a4-c97076f0b3a2.png)
Don't know if I've ever heard the history of that one ... maybe Robert can fill us in :-)

**Comment by rvirding** [comment]
I like have the "classic" Erl in the logo. I was just wondering if we could go a bit simpler. The lua logo is simple. No I don't have an alternate suggestion.

**Comment by oubiwann** [comment]
Sure thing, @rvirding ... I'll give it a ponder, and see how it goes. I might do it in increments of increasing simplicity, and you can let me know to keep going or if I've hit the sweet spot :-)

**Comment by oubiwann** [comment]
Draft 6:
![LuErl-Logo-6](https://user-images.githubusercontent.com/894251/58742311-6369af80-83e9-11e9-88fa-e12cb524e522.png)

**Comment by oubiwann** [comment]
Draft 10:
![LuErl-Logo-10](https://user-images.githubusercontent.com/894251/58742436-e6d7d080-83ea-11e9-8a16-f188241dbeaf.png)

**Comment by oubiwann** [comment]
Draft 11:
![LuErl-Logo-11](https://user-images.githubusercontent.com/894251/58742836-39fe5300-83ec-11e9-957e-74defa1bdb41.png)

**Comment by oubiwann** [comment]
I'll stop there for now, and see what direction you like ...

**Comment by oubiwann** [comment]
Actually, one more small tweak ... bringing the text colors into the same colour family as the moon.

Draft 12:
![LuErl-Logo-12](https://user-images.githubusercontent.com/894251/58754318-e266f280-8492-11e9-91bd-1e0a6a3a7138.png)

**Comment by oubiwann** [comment]
Draft 13, darker blue around the moon (it is space, after all ...):
![LuErl-Logo-13](https://user-images.githubusercontent.com/894251/58754326-2c4fd880-8493-11e9-8638-c0685a52f708.png)

**Comment by oubiwann** [comment]
Maybe the flag on the moon is too referential to geopolitics? 

We could drop the flag and put "Lu" on the crescent and "Erl" in the umbra (shadow) ...

**Comment by jchassoul** [comment]
That sounds very nice, I like how you are iterating and making it simple I'm sorry my friend could not join us after all, can't wait to see your last idea.

**Comment by oubiwann** [comment]
So ... I'm not quite sure how I feel about this (though it does have possibilities, and if others like it, I'll immediately feel better about it!):
 * The two fonts don't match very well ... in particular, the sizes (upper and lower case) and orientation
 * Not sure if the color of "Lu" is quite right
 * Placing the "Lu" so that the "L" top and bottom are equidistant from the edges of the circle doesn't allow for the "Erl"'s "E" to do the same with the umbra; rotating the "Erl" more so that this does work out, causes the angle to be rather steep ...
 * I think I might like to make the "Lu" larger, but that will require a larger crescent ...
 * Another possibility might be to put the LuErl higher ...

Draft 14:
![LuErl-Logo-14](https://user-images.githubusercontent.com/894251/60126650-14970780-9754-11e9-9463-73b124cb2ec0.png)

**Comment by oubiwann** [comment]
Draft 15, higher placement:

![LuErl-Logo-15](https://user-images.githubusercontent.com/894251/60127121-11504b80-9755-11e9-81af-80d2c7595c9d.png)

**Comment by sbuttgereit** [comment]
Since opinions are cheap... here's mine :-)

The larger issue to my eyes is one of balance.  The crescent dominates and the lower right quadrant seems "empty" somehow since all the more visual draw is to the upper left... the only counter balance to the crescent and the "Lu" is the "Erl" and the "Erl" is giving it's weight to the upper part of the image...
Draft 14 has this issue, Draft 15 seems to accentuate it to my eyes.

To my eyes it almost looks like the crescent would be more comfortable wrapping around the whole word a bit more, with perhaps a different tilt, rather than acting as a split between the two parts... letting font and color to take to role of separating the word parts.  The downside to that is that it would look more generic.

I do agree that the contrast between the Lu and the other darker parts makes the Lu color a bit ambiguous.

Sorry for chiming in uninvited...

**Comment by oubiwann** [comment]
@sbuttgereit nah, no worries -- your input _is_ valuable! (and correct, I believe). Will ponder more ...

**Comment by oubiwann** [comment]
Wait, what about a _rocket_! The nice thing about a flag was the it gave a space to place the fonts without having to fit in the crescent & umbra. Lemme see if there's a way to do this simply ...

**Comment by llelf** [comment]
How about draft 15 + cheese?

-----
Semi-offtopic:

> The lua logo is simple. No I don't have an alternate suggestion.

Wow, lua logo is great

![lua logo](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Lua-logo-nolabel.svg/512px-Lua-logo-nolabel.svg.png)

**Comment by oubiwann** [comment]
Rocket didn't work; also, couldn't figure out how to get a good setup with cheese for the fonts. 

I did juggle sizes, experimented with a larger crescent, and added a gradient to one letter ... which is okay for web graphics, but would be tricky (or expensive) for printing t-shirts ...

Not wild about the optical illusion of the different "u" stems looking like they are different sizes (they're not).

Draft 18:
![LuErl-Logo-18](https://user-images.githubusercontent.com/894251/60136994-4b2c4c80-976b-11e9-90ca-f49cea20c9a6.png)

**Comment by jchassoul** [comment]
Same as Draft 18 with 3 colours instead of 5.

![60136994-4b2c4c80-976b-11e9-90ca-f49cea20c9a6](https://user-images.githubusercontent.com/874267/60305370-8e1c2a80-98f9-11e9-9ff0-6c15e6384cb7.png)

![60136994-4b2c4c80-976b-11e9-90ca-f49cea20c9a62](https://user-images.githubusercontent.com/874267/60305385-983e2900-98f9-11e9-8ac1-bedd262e1946.png)

**Comment by aachh** [comment]
I know it's supposed to be like this, but in my opinion the askew 'erl' might look like a mistake to someone who doesn't know how the original Erlang logo looks like. Still really appreciate the designs, kudos!

**Comment by oubiwann** [comment]
Was just thinking about the logo this morning -- so cool to then see updates here :-)

@jchassoul Nice! I like these tweaks, especially the second one.

@aachh  Yeah, I have similar feelings... I think that it could either be straightened, or offset below the Lu, so that it's more visually obviously a part of the design ...

**Comment by jchassoul** [comment]
@oubiwann https://luerl.org I've updated the microsite with the logo, the website and docs still need lots of updates and general improvements, hopefully I can iterate more into things, feedback and contributions to the wiki are all welcome!

**Comment by rvirding** [comment]
@oubiwann @jchassoul I like the last suggestion for the logo. On thought I have is to maybe move the text down slightly so the Lua part of the text is a little below the middle of the circle. Not much down just a little. Then I will take it and use it.

Jean I cannot access the https://luerl.org site, is it still alive?

**Comment by oubiwann** [comment]
Draft 19

Okay, I've got yet another draft, taking not only @rvirding's suggestions into account, but also some of the thoughts I've had since the last update, with an eye towards simplicity ;-) 

What do you think about this? 
![image](https://user-images.githubusercontent.com/894251/84793102-54d14480-afba-11ea-8be8-bc00af568b93.png)

Note that I reverted to the border larger, since it looks better in different sizes:
![image](https://user-images.githubusercontent.com/894251/84793156-687cab00-afba-11ea-80a7-d349a6013ae8.png)

Other notes:
* The border has gone back to the darker color of Draft 15, as this appearance has aged better; for my eyes, the lighter border looked nice originally, but now ... less so.
* Additionally, I've tested this against dark backgrounds (e.g., the "Github Dark" theme) and it looks just as good on that (it's tricky to accomplish that in a single logo, looking good against light and dark backgrounds)
* The bottom of the "E" is exactly level with the bottom of the "u" (the curves in fonts often dip below the baseline, e.g., the bottom of the u's stem is higher than its curve).
* The "E" is actually further away from the "u" than the "u" is from the "L" -- when everything was the same distance, the "Erl" looked _way_ too close; by backing it further away, the distances actually look the same, now

Other possible tweaks:
* The Erl might look better if it was bumped another smidge or two to the right
* The Lu might look better in the small, if its boarder was a little wider
* Both the Lu and the Erl could be increased in size so that they are equally distant from the encompassing circle

**Comment by oubiwann** [comment]
Draft 20

I couldn't resist making the tweaks from the previous draft ;-)

![image](https://user-images.githubusercontent.com/894251/84796029-cfe82a00-afbd-11ea-92f1-2fd75d4b9e88.png)


![image](https://user-images.githubusercontent.com/894251/84796008-c8288580-afbd-11ea-8f0b-a5d5425d8f12.png)

I don't like the u's overlap into the dark area ... gonna try something for that.

**Comment by oubiwann** [comment]
Draft 21:

![image](https://user-images.githubusercontent.com/894251/84796831-b98e9e00-afbe-11ea-96e1-bc4f79a008a2.png)

![image](https://user-images.githubusercontent.com/894251/84796841-bd222500-afbe-11ea-9987-343095aa394e.png)

**Comment by jchassoul** [comment]
In draft 19 I feel the borders are to much and become artifacts of its own around things, I like the new draft 20 but maybe that border is too big since is almost the same size as the letters L and U?

I like draft 20 and 21... maybe is not that bad that they are the same size but then I feel that we need the same margin in between the border and the Letters at the beginning of the ( L and l ) at the end.

The website is up again, it needs the new logo and more love in its content!

**Comment by oubiwann** [comment]
Draft 22

Here's another draft ... there are very few geometries that allow for both a crescent and completely separated backgrounds:

![image](https://user-images.githubusercontent.com/894251/84797878-eabb9e00-afbf-11ea-86ed-167a4f8f3a67.png)

![image](https://user-images.githubusercontent.com/894251/84797897-f018e880-afbf-11ea-86e2-f2c379610a34.png)

**Comment by oubiwann** [comment]
As for the distance to the border, I used the lower-left of the "L" and the upper-right of the "l" ...

**Comment by oubiwann** [comment]
I'm not going to post Draft 23, but in that one I raised the height of the "L" a bit, to better match the "E" and I lowered the height of the "u" a smidge to better match the height of the "r".

**Comment by jchassoul** [comment]
Yes I see, they match, but I believed that space is smaller than the size of the border of the logo, the blue circle.

I like Draft 22, my only suggestion is that the size of the border and the distance to the border be the same or the border smaller than the distance to it, since the current way make the font appear "to big" for the circle, I think if the distances are the same as the border size it will gain more symmetry

**Comment by jchassoul** [comment]
Draft 22 is up https://luerl.org

**Comment by oubiwann** [comment]
@jchassoul I see what you're saying -- yeah, and I agree; I'll post a draft 23 after my next meeting (which will also include the minor font tweak I mentioned above).

**Comment by oubiwann** [comment]
Draft 23

Okay, in this one I made the border smaller ... it's actually narrower than the sans serif font, but there's an optical effect that makes it look larger ...

![image](https://user-images.githubusercontent.com/894251/84818924-ddf97300-afdc-11ea-9a3b-9e017b07214b.png)

![image](https://user-images.githubusercontent.com/894251/84818961-ed78bc00-afdc-11ea-879d-687afecf5a5c.png)

**Comment by jchassoul** [comment]
I love it <3

**Comment by oubiwann** [comment]
Yay!!! Let's see what @rvirding says ... maybe we have a winner? 😄

**Comment by oubiwann** [comment]
It's kinda fun to scroll through this ticket and watch the history unfold 😉

**Comment by rvirding** [comment]
I love it! 😆  Let's go with 23! Now I have something I can put in the Luerl slack. And I will make stickers as well. :smile:

**Comment by rvirding** [comment]
Btw @jchassoul I like what you are doing with https://luerl.org/

**Comment by rvirding** [comment]
@oubiwann Send me the files and I will start using them. Btw you are not in the luerl slack so I can't reference you in it. Snap snap, grin grin, wink wink, nudge nudge, say no more! :wink:

**Comment by oubiwann** [comment]
Okay, here's the final draft (/me quickly renames it from Draft 23 ...) zipped in SVG format, which will suit all of your hi-res needs ;-) 

[LuErl-Logo-v1-final.svg.zip](https://github.com/rvirding/luerl/files/4814167/LuErl-Logo-v1-final.svg.zip)

Notes
* I can provide hi-res png exports of this, too.
* All of this work has been done in Affinity Designer (way cheaper than Adobe's products, and much more convenient on the Mac than using Inkscape), and I exported from Affinity to SVG; let me know if there are any issues with the vector components.
* There is one layer set to invisible, but when enabled it will provide the lighter, less saturated dark side of the moon (as seen in Draft 19).

It's so cool to have v1 done, now! Please share pics of stickers when those are made, too!!

**Comment by rvirding** [comment]
We now have a logo.
