### ISSUE TITLE
luerl.do returns raw table reference instead of decoded value

### ISSUE THREAD

**Issue by DarkMarmot** [rvirding/luerl#114]
While working with :luerl_sandbox, I noticed I could easily extract primitive values but not tables in function returns.

I think the issue is that `:luerl.do` works such that (in Elixir, apologies):

`:luerl.do("return {x=7}") |> elem(0)` 
yields `[tref: 13]`

Is it missing a decoding step in this function?

**Comment by rvirding** [comment]
Yes and no. It is not missing one as it was never meant to have one. There are 2 groups of functions in `luerl.erl`, those that encode/decode and those that don't. Unfortunately it is not as consistent as it could/should be.

So `do`, `do_file` don't decode while `eval` does decode. `load` and `load_file` don't decode but it isn't really relevant here.

For the remaining functions `call_chunk/2/3`, `call_function/2/3`, `call_method/2/3`, `get_table/2` and `set_table/3` these do encode/decode. However, they all have alternate functions with the names ending in `1` which don't decode. So `call_function/3` encodes/decodes while `call_function1/3` doesn't. The ones which don't encode/decode are much better when you want to chain them together as you pass references to the actual data in the Luerl state not making copies of them. This means than updating them will work properly.

Unfortunately the way of naming isn't that good, perhaps it should be called `call_function_raw/3` instead? Also it isn't consistent as all the functions which don't encode/decode don't follow the same naming rules.

I would like to do a proper renaming of the functions but unfortunately it would be backwards incompatible which is not a Good Thing. And having 2 modules `luerl` and `new_luerl` is not any better.

Note that Luerl supports recursive tables just the same as Lua does but these can not be decoded into Erlang data. If you try and decode a recursive structure you get a `recursive_data` error.

**Comment by DarkMarmot** [comment]
Ahh, ok! Thanks for the clarifications!

I was trying to get tables returned through `:luerl_sandbox` -- which calls into `do` and thus doesn't handle decoding. I thought I'd be able to route the returned `:tref` and state into `:luerl.decode` but wasn't able to get that to work (I need to up my Erlang game).

Thanks!

**Comment by DarkMarmot** [comment]
Oh, I think I figured out my problem! :)

I can decode the table against the state -- I was getting messed up because Elixir's syntactic sugar for keyword lists made me forget that the `:tref` was in a list since Lua returns a list of results.

Thanks so much!
