### ISSUE TITLE
Loading third-party library redis failed

### ISSUE THREAD

**Issue by LvCodeing** [rvirding/luerl#124]
parse.lua
-------------------------------------------------------------------------------------------------
function on_message_publish(clientid, username, topic, payload, qos, retain)
     local redis = require('redis')
     local params = {
          host = '127.0.0.1',
          port = 6379,
    }

     local client = redis.connect(params)
     client:auth('123456')
    client:select(1) -- for testing purposes

     return topic, payload, qos, retain
end

function register_hook()
     return "on_message_publish"
end

-------------------------------------------------------------------------------------------------

Error message:

{{lua_error,
{no_module,<<"redis">>,<<"'./redis.lua' './redis/init.lua' ">>},
{luerl,{array,14,100,undefined,
{{{table,
{array,0,10,nil,10},
{{{{empty,
<<"_G">>,{tref,0},empty,
<<"_VERSION">>,
<<"Lua 5.2">>,
empty},
<<"assert">>,
{function,
#Fun<luerl_lib_basic.1.127600018>},
{empty,
<<"bit32">>,

**Comment by zoush2016** [comment]
cmmond:
      lua parse.lua  is ok.

**Comment by manuel-rubio** [comment]
@zoush2016 I'm afraid that Redis library isn't available by default for Lua and of course, it's not available for Luerl. You could create an Erlang project inserting a dependency like this:

https://hex.pm/packages/eredis

And then, create an interface publishing the functions you want to use in the Lua side.

This library is 100% Lua, maybe you could use it as well, but I didn't try it before:

https://github.com/nrk/redis-lua

**Comment by codeadict** [comment]
@LvCodeing I can recognize this code from VerneMQ. We have Redis support by exposing the `eredis` package so the API is limited to what we provide via the internal Erlang API. There is no support for external libraries at this point. You can use it like (without loading any library):

```lua
config = {
    pool_id = "your_cool_pool"
}
key = "yourkey"
redis.ensure_pool(config)
res = redis.cmd(pool, "get " .. key)
```
 You can read the implementation in https://github.com/vernemq/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_redis.erl, is rather simple and only has 2 functions exposed, onew for starting the connection pool and other to run raw Redis commands.
