### ISSUE TITLE
Whether to support multi-lua script file parsing

### ISSUE THREAD

**Issue by LvCodeing** [rvirding/luerl#127]

**Comment by rvirding** [comment]
@LvCodeing sorry I cannot see anything here.

**Comment by jchassoul** [comment]
@LvCodeing Luerl do support "multi-lua script file parsing", if that means multiple Lua processes in the environment reading, loading and executing different Lua files.

**Comment by rvirding** [comment]
Luerl does not implement Lua processes.

**Comment by davydog187** [comment]
@LvCodeing closing as there's not a clear request here, please reopen if you can elaborate
