### ISSUE TITLE
Update luerl in hex.pm

### ISSUE THREAD

**Issue by badlop** [rvirding/luerl#142]
First of all, congratulations for this library!

I collaborate in a project that uses it, but we are still using the ancient 0.3 version, as all the new releases lack some of the release steps:

0.3
- [x] correctly versioned in luerl.app.src
- [x] tagged in git
- [x] [published in hex.pm](https://hex.pm/packages/luerl)

0.3.1
- [x] correctly versioned in luerl.app.src
- [ ] tagged in git :x:
- [x] published in hex.pm

0.4
- [ ] correctly versioned in luerl.app.src :x:
- [x] tagged in git
- [x] published in hex.pm

1.0 (a.k.a. v1.0)
- [x] correctly versioned in luerl.app.src
- [x] tagged in git
- [ ] published in hex.pm :x:

Would it be possible to publish 1.0 in hex.pm?

**Comment by rvirding** [comment]
I will try and fix this. I don't know about hex.pm as I am not the one who has put it there.

**Comment by rvirding** [comment]
@badlop I have checked and it will be difficult to fix the issues with 0.3.1 and 0.4. In both cases it would be possible to create specific 0.3.1 and 0.4 branches which fix the issues and tag them, but I don't really know if it is worth the effort. What do you think.

And as I said before I never worked against hex.pm so I don't know how to do it and who can go and add things to this in hex.pm.


As 0.3.1 was never merged from `develop` into `master` so doing it now will be difficult but I could make a specific 0.3.1. branch and fix it there. As for 0.4 it was merged into `master` which has now gone on so onne solution would be to make a specific 0.4 branch and fix it there but I don't really know if it is worth the effort

**Comment by rvirding** [comment]
I have now checked on hex.pm and Luerl was aded by a user called Licenser. I don't know if that allows me to upgrade it with a new version or whether he must do it. Or if I can take it over. Having 2 different Luerls would probably just be confusing.

**Comment by badlop** [comment]
Thanks! I see you started publishing in Hex.pm

Now luerl 1.0.0 can be downloaded as a package from hex.pm by rebar3 and Elixir's mix, and cached locally.
