### ISSUE TITLE
should luerl_new:load convert error atom to lua_error?

### ISSUE THREAD

**Issue by samaaron** [rvirding/luerl#159]
The return tuple for the error case in ` luerl_new:do` and friends is documented as `lua_error`. However, I see `error` and I believe that's because `load` does not try/catch and convert the error atom as happens within `call_function`. This means that the `luerl_comp:string` error atom is exposed.

I'm therefore wondering what the intention is - is the documentation the intended behaviour or the currently observed behaviour?

**Comment by samaaron** [comment]
Hi @rvirding,

I'm using version 1 from Elixir:

```
"luerl": {:hex, :luerl, "1.0.0", "1b68c30649323590d5339b967b419260500ffe520cd3abc1987482a82d3b5a6c", [:rebar3], [], "hexpm", "c17bc45cb4b0845ec975387f9a5d8c81ab60456698527a29c96f78992af86bd1"},
```

This was pulled in via Elixir's mix after declaring the following dep: `{:luerl, "~> 1.0"}`

The error tuple containing the `error` atom is the result of a syntax error and can be replicated with:

```
:luerl_new.do_dec("dfdf333" lua_state)
```

It returns:

```
{:error, error, state}
```

**Comment by samaaron** [comment]
Ah, looks like v1.0 is rather old. I was looking at the source provided in the deps folder pulled down from hex to see what was happening rather than looking at the `develop` branch on Github. 

Seems that the latest code does what the documentation describes:

https://github.com/rvirding/luerl/blob/develop/src/luerl_new.erl#L226

Is there anything holding back from getting a new release tagged?

**Comment by samaaron** [comment]
Actually after playing around, both the latest development version and v1.0 appear to behave similarly here:

```
iex(2)>  :luerl_new.do_dec("3434ddd", l)
{:error, [{1, :luerl_parse, [~c"syntax error before: ", [~c"3434"]]}], []}
```

**Comment by rvirding** [comment]
The reason for this is that `lua_error` is returned when running Lua code. The compiler in this sense does not really return a Lua error hence the `error`. When running say `loadfile` from within Lua then the compiler error is caught, all erros actually,  and a string describing the error is returned.
