### ISSUE TITLE
GC run required even when nothing happens

### ISSUE THREAD

**Issue by hce** [rvirding/luerl#49]
I'm using a couple of hundred erlua states within one erlang process and I'm calling a tick function defined in Lua for each of the erlua states once per second. I've noticed that the erlang process's state is growing by ~1MB each tick, even when the Lua tick function was empty like this:
  function tick(deltaTime)
    -- do absolutely nothing
  end

The function is called like this:
    {_IgnoreResult, NewLuaState} = luerl:call_function([tick], [DeltaTime], LuaState)

The Lua module does define some global variables to keep state, but they are not touched from the tick function.

Calling the erlua garbage collector solved the problem. Not sure if it is an issue, but I'd be nice to know the reason for this behaviour. ;-)

**Comment by rvirding** [comment]
That would be about a few KB per call. That seems quite a lot. There are some cases when the environment of a function can grow or at least needs to be referenced but the size surprises me. Would it be possible to see the code so I can try and work out what is going on?

**Comment by hce** [comment]
Okay, after looking into it again it looks like the continuous growth only happens when you pass complex structures to the function, like a list. Which makes sense, because an internal erlua structure needs to be created and without running the GC erlua has no way of knowing if the structure was already referenced somewhere. So I guess this is a non-issue. Sorry for the noise!

Nevertheless, here is an example code snippet to reproduce it:

run() ->
    {_Result, State0} = luerl:do("local state = {a=1, b=2}\nfunction init() state.c = 3 end\nfunction tick(deltaTime)\nend\n"),
    io:format("Size State0: ~p~n", [size(term_to_binary(State0))]),
    {_, State1} = luerl:call_function([init], [], State0),
    DeltaTime = [10],
    State3 = lists:foldl(
               fun(Seq, State) ->
                       {_, State2} = luerl:call_function([tick], [DeltaTime], State),
                       State2
               end, State1, lists:seq(1, 100000)),
    io:format("Size State3: ~p~n", [size(term_to_binary(State3))]),
    done.

**Comment by rvirding** [comment]
Yes, the reason is that you are passing a new table into every call of `tick`. The `[10]` list is encoded every time to a table `{[1]=10}` which is entered into the luerl table area. The system cannot do anything smart about this in this case as tables are shareable global state so they must exist in the table area. The `tick` function doesn't know anything about its caller and the caller of `tick` does not know what it does.

You could explicitly create the table first using `luerl:set_table/3` and then call the functions using `luerl:cal_function1/3` but that is not quite the same thing as you are then explicitly sharing the same table.

**Comment by hce** [comment]
Ok, it's no issue then but normal behaviour I wasn't aware of when using luerl that way. AFAICT the GC is never called by luerl itself but needs to be called explicitely by the user of luerl manually, correct? A guide on how to best use the GC would help a lot IMHO. I at first didn't even consider calling luerl's gc myself because the README declares it as an experimental feature.

**Comment by rvirding** [comment]
Sorry for not commenting earlier.

No, the GC is never called by luerl itself. The main reason is that I could not work out a decent heuristic about *when* to call. For example there is no heap as such I can check to see how much luerl memory we are using and when it fills. So it is left up to the caller to do. Currently calling it from inside luerl is a noop so you need to call it from the erlang level.

This might be useful if you want to reuse the initial state for each call as you can just throw away the returned state and not waste time doing a gc.

**Comment by Zert** [comment]
I run `erlang:garbage_collect()` after each `luerl` function evaluation for each process, otherwise my erlang node consumes too much memory. Though each of my process calls `erlang:garbage_collect()` only few times per minute, this is quite enough.

**Comment by rvirding** [comment]
Are you calling `luerl:gc` before calling `erlang:garbage_collect`?

The default erlang collector is a generational collector so it takes longer time to collect everything. When you call `erlang:garbage_collect` you do a full collection for that process. You can control the process collector with `spawn_opts` to make it do a full collection more often.

**Comment by Zert** [comment]
No, I don't call `luerl:gc`. Thank you for advice, Robert!
