### ISSUE TITLE
lua_error when set_table calls

### ISSUE THREAD

**Issue by kvratkin** [rvirding/luerl#54]
Hi Robert,

I want create table from Erlang. I do

``` erlang
-module(hello_table2).
-export([run/0]).

run() ->
    State0 = luerl:init(),
    {ok, Chunk, State1} = luerl:load("print(\"Hello, Chunk!\")", State0),
    {_Ret, State2} = luerl:do(Chunk, State1),
    State3 = luerl:set_table([ftbl, field], value, State2),
    {Val, State4} = luerl:get_table([ftbl, field], State3),
    io:format("(1) ~p~n", [Val]).
```
And I got huge list of lua errors started from this line
{"init terminating in do_boot",{{lua_error,{illegal_index,nil,<<"field">>},

Where is my mistake?

**Comment by Zert** [comment]
Hello

You trying to modify lua value `ftbl.field`, but there is no `ftbl` in global context yet.
Try this code:
```erlang
-module(hello_table2).
-export([run/0]).

run() ->
    State0 = luerl:init(),
    {ok, Chunk, State1} = luerl:load("print(\"Hello, Chunk!\")", State0),
    {_Ret, State2} = luerl:do(Chunk, State1),
    State3 = luerl:set_table([ftbl], [], State2), %% Create `ftbl` first
    State4 = luerl:set_table([ftbl, field], value, State3), %% Then assign its field `field`
    {Val, _State5} = luerl:get_table([ftbl, field], State4),
    io:format("(1) ~p~n", [Val]).
```

**Comment by rvirding** [comment]
Yes, luerl gives very basic error messages, not in the same class as the standard Lua implementation. Here it accesses the variable `ftbl` and gets its value, in this case `nil`, then tries to set the key `field`. It then sees that there is no table and returns the error that it is an illegal index to `nil`.

**Comment by rvirding** [comment]
Btw there is an IRC channel #luerl on freenode if you want to chat about luerl.

**Comment by kvratkin** [comment]
Thank you, guys. It works.
And sure, I'll subscribe on luerl google group because I'm going to use luerl hard.
I feel questions about luerl internals will come ;)
