### ISSUE TITLE
Erlang lib that can deal with tables

### ISSUE THREAD

**Issue by dergraf** [rvirding/luerl#55]
Hi there.

I am playing with exposing an Erlang database driver to Luerl. With simple queries the string datatype works great. However for more complex arguments I would like to pass a Lua table type to the Erlang lib and convert it to either proplist or maybe map. What is the suggested way for doing this?

Cheers,
Andre

**Comment by rvirding** [comment]
In the luerl module there are the function luerl:encode/2 and luerl:decode/2 for encoding erlang data into Lua and vice-versa. Tables are represented as Erlang key-value property lists. The conversion is quite straight-forward except that it is impossible to decode circular mutually recursive Lua data structures into Erlang, erlang can't do mutually recursive structures.

Are you writing Lua functions to be called from within Lua to do this or are you intending to call Lua from Erlang with values from the database and get values back from Lua which you then insert into the database?

**Comment by dergraf** [comment]
Oh, somehow I completely missed those functions. I will check them out.

Currently, I expose an erlang API so a Lua Script can execute a database statement. As an example I expose the main emysql API to Luerl.

**Comment by dergraf** [comment]
Great. The decode/encode functions are working for me.

**Comment by rvirding** [comment]
One final comment: only the decode the 'develop' branch has a check for circular structures and generates an error. The one in 'master' does not do that yet.
