### ISSUE TITLE
Incorrect function signature for __newindex metamethod

### ISSUE THREAD

**Issue by t-mw** [rvirding/luerl#57]
The function signature for `__newindex` in native Lua is `function (table, key, value)`, while in luerl it is `function (key, value)`. I personally don't have a use for the `table` argument, but thought I'd create an issue since it could be useful for people migrating existing scripts to luerl.

**Comment by rvirding** [comment]
This is definitely a bug. I never tested it and no-one has used this feature. I will fix it.
