### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by rbarlow** [rvirding/luerl#60]
Would you consider tagging your current HEAD as a release? It is being used by ejabberd-16.02, and it would be nice to package it as a formal release instead of a commit. Thanks!

**Comment by rvirding** [comment]
How do you mean? Tag the master branch? Would v0.2 be ok? I will be merging develop into master real soon now, but I can make that v0.3.

**Comment by rbarlow** [comment]
Hello @rvirding! Yeah, the head of the master branch is in use by all ejabberd-16.02 users so it would be nice to be able to refer to that by a tag instead of just a commit hash. v0.2 would be great. Thanks!

**Comment by rvirding** [comment]
OK, done. There is now a v0.2 tag on the old head of master and a v0.3 tag on the new head which includes some mainly internal updates.

**Comment by rbarlow** [comment]
Thanks so much @rvirding, and thanks for creating wonderful Free Software!

**Comment by rvirding** [comment]
My pleasure. I forgot to ask what you are using it for in ejabberd? I couldn't see anything on the website.

**Comment by rbarlow** [comment]
Hello @rvirding,

It looks like your project is used in a migration script to help users migrate from prodody to ejabberd. It was introduced in this commit:

https://github.com/processone/ejabberd/commit/b20db3b73678024b4fb786435355ab66f21de351

**Comment by rvirding** [comment]
That's fantastic. Tell them to let me know how it goes and if they run into problems or strange behaviour.
