### ISSUE TITLE
Luerl does not handle nil input arguments in conv_list

### ISSUE THREAD

**Issue by novabyte** [rvirding/luerl#66]
This seems like a bug to me:

```
inputs = ["one", nil, "three", 20.0]
res = luerl_lib:conv_list(inputs, [:lua_string, :lua_string, :lua_string, :integer])
erlang:display(res)
```

This gives back `nil` because `luerl_lib:conv_list` bails out if it has a `nil` input argument instead of propogating `nil` forwards to the output list.

**Comment by rvirding** [comment]
That is the intent of the function. It is not a "general" function and was designed to be used for testing the types and converting input arguments to a "lua" function implemented in Erlang and in this sense `nil` is not a legal string. At least the library functions which use it require this.

**Comment by novabyte** [comment]
@rvirding I see - I'll close the issue and work around it in my own code.

**Comment by rvirding** [comment]
Just curious. What are you doing? Do you have any other questions about things like this?

I would be a bit careful about using "internal" functions, it is really only the module `luerl` which is defined. The internal interface may change as I have plans for the emulator. There won't be any changes for the Lua 5.2 version but maybe for the future 5.3.

**Comment by novabyte** [comment]
@rvirding Right now we've built a code execution service which uses Luerl to power the VM runtime. It's a bit like AWS Lambda or Google Cloud Functions although with some of our own enhancements/design decisions. I plan to write a blog post announcement about the new system (aimed at our developer community) but I'll send it your way in case you're interested.

I've made some notes as I've worked with Luerl and will neaten them up as a private Gist to send to you in case it helps with the changes you have planned for Luerl to support 5.3. I'd love to contribute to the project as you plan out changes. Let me know if/how I can help.

Luerl is brilliant. Thanks :smiley:

**Comment by rvirding** [comment]
Thank you :-)

Be aware of one thing, you have to call the garbage collector from erlang through `luerl:gc()`. It is not called automatically  and the lua call `collectgarbage` is currently a noop as I could not convince myself that it was safe. It will be fixed.
