### ISSUE TITLE
os.getenv("ENV_VAR") return nil

### ISSUE THREAD

**Issue by georgepoenaru** [rvirding/luerl#67]
Hi,

I need to use an env var `($API_STAGE)`. So I used:

`stage = os.getenv("API_STAGE")`

Look's like luerl does support `os.getenv`

However it does return `nil` even if the variable is already set:

```
vernemq@broker-3325152631-yg68e:/$ echo $API_STAGE
dev 
```

**Comment by rvirding** [comment]
Hmm, are you sure that the environment variable is set in the erlang process? Try doing `os:getenv("API_STAGE").` in the erlang shell to check. The following is a test from the erlang shell:

    18> f(R), {R,_}=luerl:do("path = os.getenv(\"PATH\") ; print(path); return path"), R.
    /usr/local/lib/erlang/erts-8.0/bin:/usr/local/lib/erlang/bin:/Users/rv/bin:/usr/local/git/bin:/usr/bin: /bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Library/TeX/texbin 
    [<<"/usr/local/lib/erlang/erts-8.0/bin:/usr/local/lib/erlang/bin:/Users/rv/bin:/usr/local/git/bin:/usr/bin:/bin:/usr"...>>]

**Comment by georgepoenaru** [comment]
@rvirding  Thank you. Indeed, Erlang Shell doesn't see the variable.
