### ISSUE TITLE
Change random:uniform to rand:uniform

### ISSUE THREAD

**Issue by bendiken** [rvirding/luerl#70]
When building Luerl on R19, the following deprecation warnings are output in an otherwise clean compile:

    ==> luerl
    erlc -o ./src src/luerl_scan.xrl
    erlc  -o ./ebin src/luerl_scan.erl
    erlc -o ./src src/luerl_parse.yrl
    erlc  -o ./ebin src/luerl_parse.erl
    erlc  -o ./ebin src/luerl.erl
    erlc  -o ./ebin src/luerl_app.erl
    erlc  -o ./ebin src/luerl_comp.erl
    erlc  -o ./ebin src/luerl_comp_cg.erl
    erlc  -o ./ebin src/luerl_comp_env.erl
    erlc  -o ./ebin src/luerl_comp_locf.erl
    erlc  -o ./ebin src/luerl_comp_peep.erl
    erlc  -o ./ebin src/luerl_comp_vars.erl
    erlc  -o ./ebin src/luerl_emul.erl
    erlc  -o ./ebin src/luerl_lib.erl
    erlc  -o ./ebin src/luerl_lib_basic.erl
    erlc  -o ./ebin src/luerl_lib_bit32.erl
    erlc  -o ./ebin src/luerl_lib_debug.erl
    erlc  -o ./ebin src/luerl_lib_io.erl
    erlc  -o ./ebin src/luerl_lib_math.erl
    src/luerl_lib_math.erl:213: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
    src/luerl_lib_math.erl:215: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
    src/luerl_lib_math.erl:218: Warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
    src/luerl_lib_math.erl:228: Warning: random:seed/3: the 'random' module is deprecated; use the 'rand' module instead
    erlc  -o ./ebin src/luerl_lib_os.erl
    erlc  -o ./ebin src/luerl_lib_package.erl
    erlc  -o ./ebin src/luerl_lib_string.erl
    erlc  -o ./ebin src/luerl_lib_string_format.erl
    erlc  -o ./ebin src/luerl_lib_table.erl
    erlc  -o ./ebin src/luerl_sup.erl
    erlc  -o ./ebin src/ttdict.erl

It seems that going forward, use of the [random](http://erlang.org/doc/man/random.html) module should be replaced by the [rand](http://erlang.org/doc/man/rand.html) module.

I'd be happy to work up a patch for this and submit a pull request. However, it does mean dropping R17 support--any objections?

**Comment by tisba** [comment]
In https://github.com/rvirding/luerl/pull/58#issuecomment-196224665 it looks like @rvirding does want to keep support for older versions of Erlang.

**Comment by rvirding** [comment]
Yes, I do want to support older versions. However I do have a reasonable way of testing Erlang version at system build time which will allow me to handle this.

**Comment by bendiken** [comment]
Thanks! I confirm that this does indeed resolve the deprecation warnings, and Luerl now compiles cleanly on R19.
