### ISSUE TITLE
hex package

### ISSUE THREAD

**Issue by Licenser** [rvirding/luerl#72]
It would be really nice to have a hex package for luerl!

I think it's pretty much only needed to run `rebar3 hex publish` if not I'm happy to publish it, work out all the kinks, prepare a PR and then hand the package over.

**Comment by rvirding** [comment]
I will have to try it and see how it goes.

**Comment by Licenser** [comment]
I'll have something done this week - unless I forget it, then feel free to yell at me ;)

**Comment by narrowtux** [comment]
boop?
