### ISSUE TITLE
Is math.randomseed unsafe?

### ISSUE THREAD

**Issue by bopjesvla** [rvirding/luerl#78]
If I'm not mistaken, math.randomseed can set the global seed, which is a bad thing in sandboxed environments. A possible solution is to attach a randomness state to every Lua VM.

**Comment by rvirding** [comment]
Yes, math.randomseed does set it globally but global in this respect means local for each Lua VM. So the randomness state is local to each Lua VM.

The reason it works this way is that each Lua VM is a separate Erlang process and the random seed is local to the process.

**Comment by bopjesvla** [comment]
I have a poorer understanding of luerl's architecture than I thought then. Thanks for the explanation!

**Comment by bopjesvla** [comment]
No, I do seem to be right:

```elixir
iex(13)> :luerl.eval("math.randomseed(125); math.random(); return math.random()")
{:ok, [0.5042267877783537]}
iex(14)> :luerl.eval("math.randomseed(125); return math.random()")      
{:ok, [0.6228313323782555]}
iex(15)> :luerl.eval("return math.random()")                            
{:ok, [0.5042267877783537]}
```

One Lua state can decide the next random number of another.

**Comment by bopjesvla** [comment]
Oh, I just realised I said VM in the OP where I should have said state.

**Comment by bopjesvla** [comment]
Based on further experiments I'd guess that every process spawns its own Lua VM. So if every Lua state is managed by a different process, this cannot happen. Is that correct?

**Comment by bopjesvla** [comment]
I was using rand instead of random in my tests. math.randomseed does just set the current process's seed:

```elixir
iex(7)> :luerl.eval("math.randomseed(123)")
{:ok, []}
iex(8)> :random.uniform()
0.8997152730436226
iex(9)> :luerl.eval("math.randomseed(123)")
{:ok, []}
iex(10)> :random.uniform()
0.8997152730436226
```

**Comment by rvirding** [comment]
Yes, it sets the seed of the current process but the current process isn't the same as the luerl state. Basically the state structure contains everything except for the randomseed which is process bound. That the state is just a big data structure means that you can pass it around, copy it and run it on different processes. Of course they don't interact and share data.

This means that setting randomseed mightn't behave as expected. Maybe I should make the seed part of the state structure.

**Comment by rvirding** [comment]
I have added a comment in #79 about multiple Lua VMs and Erlang data and processes. This explains why I might make the randomseed part of the Lua state so you can move the state between processes and get a more consistent behaviour.

**Comment by bopjesvla** [comment]
The old random module does not seem to support seeding in a way that does not affect the process dictionary, so this is a breaking change.

**Comment by bopjesvla** [comment]
By breaking change I mean that it drops R17 compatibility.

**Comment by rvirding** [comment]
Sorry, I did a forced push to cleanup the commit message. I know I shouldn't do that.
