### ISSUE TITLE
Limiting memory

### ISSUE THREAD

**Issue by bopjesvla** [rvirding/luerl#79]
Another sandboxing question: how would you go about limiting a the memory of the execution of some Lua code? What potential ways do users have to circumvent memory limits?

I first thought this would be as easy as simple as tacking a max_heap_size onto the process interfacing with luerl, but I infered from #78 that computations and/or storage may be done in a separate Lua VM process. Besides that, luerl uses ETS and the process dictionary, which I'm not sure is counted as a part of the heap of the owner process.

**Comment by bopjesvla** [comment]
I see now that usage of ETS and the process dictionary are optional. I'd still like to know if I only have to limit the memory of the owner process, or other processes are involved as well.

**Comment by bopjesvla** [comment]
This was probably based on a misunderstanding.

**Comment by rvirding** [comment]
One thing I must clarify here is that the whole Lua state is contained in the `State` data structure which is threaded through the functions in the `luerl` module. Everything. So each Lua VM is only run in on Erlang process. Seeing it Lua state is just a data structure it can be passed between processes and many processes can run their own version of it. It also means that one Erlang process can maintain many separate Lua VMs but only run them interlaced but only one at a time.

**NOTE** that seeing the state is a normal Erlang data structure used in normal Erlang processes there is no implicit sharing between the Lua VMs. This irrespective of whether they are in one Erlang process or in many.
