### ISSUE TITLE
Luerl slack team

### ISSUE THREAD

**Issue by rvirding** [rvirding/luerl#81]
For those who have not seen it the is a luerl slack team at [https://luerl.slack.com/](https://luerl.slack.com/). You can join it by requesting an invite at [http://luerl-slack.herokuapp.com/](http://luerl-slack.herokuapp.com/). Some discussions might be easier there.

**Comment by negcx** [comment]
It seems the Heroku site is down for the Slack invite - is the Slack still there?

**Comment by rvirding** [comment]
The request to join is now https://erlef.org/slack-invite/luerl . This was changed in the README but not in a comment to this issue I'm afraid.

**Comment by rvirding** [comment]
The request to join is now https://erlef.org/slack-invite/luerl .
