### ISSUE TITLE
Bug in os.time() 

### ISSUE THREAD

**Issue by voluntas** [rvirding/luerl#94]
Perhaps I do not think that decimal places are included.

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:0] [hipe] [kernel-poll:false] [dtrace] [sharing-preserving]

Eshell V9.3  (abort with ^G)
1> S0 = luerl:init().
2> {ok, Chunk, S1} = luerl:load("return os.time()", S0).
3> {ok, Result} = luerl:eval(Chunk, S1).
{ok,[1524660247.463684]}
```

lua 5.2.2

```
> os.time()
1524660312
```

https://wandbox.org/permlink/DwKsOQaNw56AD84T

**Comment by rvirding** [comment]
Is this an error? All that the documentation says is that it should be the number of seconds, which this is but including the microseconds as well. 😄

**Comment by voluntas** [comment]
Thank you for reply.
As you say, this is not an error and there is no need to fix it for now.
Thanks anyway.
