### ISSUE TITLE
Interger are encode as float

### ISSUE THREAD

**Issue by zhaoweiguo** [rvirding/luerl#97]
$> cat hello.lua
> json = require("json");
B="{\"name\":123}";
print(B)
A = json.decode(B);
C = json.encode(A);
print(C);

%% run
> erl -pa ebin
erl> luerl:dofile("./hello.lua").

%% print

> {"name":123} 
{"name":123.00000000000} 

%% The print of What I want
> {"name":123} 
{"name":123}

**Comment by zhaoweiguo** [comment]
And what should i do to get what i want
tkx

**Comment by rvirding** [comment]
Which version of lua are you running?

**Comment by zhaoweiguo** [comment]
> Which version of lua are you running?

> root@iZ8vb7vqedcq5b0or4thioZ:/home/pzsh# lua
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> a="{\"name\":123}";
> json=require("json");
> c=json.decode(a);
> print(c.name)
123
> d=json.encode(c)
> print(d)
{"name":123}

**Comment by zhaoweiguo** [comment]
@rvirding And i tried lua5.3 and 5.1, got the same result
> root@iZ8vb7vqedcq5b0or4thioZ:/home/pzsh# lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> a="{\"name\":123}";
> json=require("json");
> c=json.decode(a);
> print(c.name)
123
> d=json.encode(c)
> print(d)
{"name":123}

**Comment by zhaoweiguo** [comment]
> I will try and fix it and make it return "integers" so they look like integers. Btw which version of erlang are you using? This should not be a problem for luerl.

zhaodeMac:priv zhaoweiguo$ erl
Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

**Comment by zhaoweiguo** [comment]
@rvirding Is there any plan about this issue?

**Comment by rvirding** [comment]
Yes, I am working now on making a new version of luerl which implements Lua 5.3 which has integers.

**Comment by rvirding** [comment]
5.3 has some other interesting features.Do you know that `a=0x3p4h=36` is legal syntax?

**Comment by rvirding** [comment]
Sorry @zhaoweiguo , I just turned my brain on properly now when working with the integers. The problem I think is in the printing of the floats not in the actual values. So in 5.2 all numbers are floats but the number `123.0` is _printed_ as, or _converted_ to the string `123`. However in luerl the float `123.0` gets converted to the string `123.00000000000`. The actual values are the same.

I will check if this is correct and where it happens and see if I can do a simple fix for it.

What do you do with the values?

**Comment by zhaoweiguo** [comment]
There is a platform doing something.
Other guys who using this platform want to do some other thing not so common.
So i wanted them to do this using lua plugin, so...

BTW.  I did these things using api now.
