### ISSUE TITLE
lua not support os.execute('')

### ISSUE THREAD

**Issue by dongweizhao** [rvirding/luerl#98]

**Comment by rvirding** [comment]
What does `os.execute("")` do with the output from the command? It doesn't seem to return it and I can't find anything in the docs.

**Comment by jimt** [comment]
It is discarded.  If you want the output you either need to redirect it into a file to be read later or use `io.popen`.

**Comment by dunielpls** [comment]
Think it would be acceptable to use erlang's `os:cmd(Str).`? Lua's `os.execute` returns the exit code while Erlang's `os:cmd/1` returns the stdout of the executed command as a string.
